default['java']['jdk_version'] = '7'
default['deployer']['chef-server-url'] = 'https://10.111.4.101'
default['deployer']['default-password'] = 'foobar'
default['eutester']['git-repository'] = 'git@git.qa1.eucalyptus-systems.com:qa-repos/eutester.git'
default['eutester']['git-revision'] = 'maint/4.0/testing'
default['EucaTest']['git-repository'] = 'https://github.com/viglesiasce/EucaTest.git'
default['EucaTest']['git-revision'] = 'master'
