default['java']['jdk_version'] = '8'
default['deployer']['chef-server-url'] = 'http://10.111.4.101'
default['deployer']['default-password'] = 'foobar'
default['eutester']['git-repository'] = 'http://git.qa1.eucalyptus-systems.com/qa-repos/eutester.git'
default['eutester']['git-revision'] = 'master'
default['EucaTest']['git-repository'] = 'https://github.com/viglesiasce/EucaTest.git'
default['EucaTest']['git-revision'] = 'master'
